# When defining services do not include Connected, Mgmt/ProcessName, Mgmt/ProcessVersion, Mgmt/Connection, DeviceInstance, DeviceName, 
# ProductName or FirmwareVersion these are all handled automatically by the driver

# For product id see https://gist.github.com/seidler2547/52f3e91cbcbf2fa257ae79371bb78588


# https://github.com/victronenergy/venus/wiki/dbus#ac-chargers
charger:
  ProductId:
    default: 41761 #Blue Smart IP22 Charger 12|15 (3)
  CustomName:
    default: "My Blue Smart IP22 Charger"
    persist: true
  Ac/In/L1/I:
    description: "A AC"
    format: "{} A"
  Ac/In/L1/P:
    description: "W"
    format: "{} W"
  Ac/In/CurrentLimit:
    description: "A"
    format: "{} A AC"
  NrOfOutputs:
    default: 3  
  Dc/0/Voltage:
    description: "V"
    format: "{} V"
  Dc/0/Current: 
    description: "A"
    format: "{} A"
  Dc/0/Temperature: 
    description: "°C"
    format: "{} °C"
  Dc/1/Voltage:
    description: "V"
    format: "{} V"
  Dc/1/Current: 
    description: "A"
    format: "{} A"
  Dc/1/Temperature: 
    description: "°C"
    format: "{} °C"
  Dc/2/Voltage:
    description: "V"
    format: "{} V"
  Dc/2/Current: 
    description: "A"
    format: "{} A"
  Dc/2/Temperature: 
    description: "°C"
    format: "{} °C"
  State:
    description: "0=Off; 2=Fault; 3=Bulk; 4=Absorption; 5=Float; 6=Storage; 7=Equalize; 252=External control"
  Mode:
    description: "1=On; 4=Off"
  ErrorCode:
    description: "Error Description"


# https://github.com/victronenergy/venus/wiki/dbus#solar-chargers
solarcharger:
  ProductId:
    default: 41045 # Smart Solar Charger MPPT 100/15
  CustomName:
    default: "My Smart Solar Charger"
    persist: true
  NrOfTrackers:
    default: 1  
  Dc/0/Voltage:
    description: "V"
    format: "{} V"
  Dc/0/Current: 
    description: "A"
    format: "{} A"
  Yield/Power:
    description: "kWh"
    format: "{} kWh"
  State:
    description: "0=Off; 2=Fault; 3=Bulk; 4=Absorption; 5=Float; 6=Storage; 7=Equalize; 252=External control"
  Load/I:
    description: "A"
    format: "{} A"
  Pv/0/P:
    description: "A"
    format: "{} A"
  Pv/V:
    description: "V"
    format: "{} V"
  MppOperationMode:
    description: "0=Off; 1=Voltage or Current Limited; 2=Maximum Power"
  ErrorCode:
    description: "Error Description"

# https://github.com/victronenergy/venus/wiki/dbus#temperatures
temperature:
  ProductId:
    default: 41314 # Generic Temperature Input
  CustomName:
    default: "My Temperature Sensor"
    persist: true
  TemperatureType:
    description: "Battery, Fridge or Generic"
    persist: true
    default: 2
    min: 0
    max: 2
  Status:
    description: "0=Ok; 1=Disconnected; 2=Short circuited; 3=Reverse polarity; 4=Unknown"
    default: 0
    min: 0
    max: 4
  Temperature:
    description: "C"
  Pressure:
    description: "hPa"
  Humidity:
    description: "%"


# https://github.com/victronenergy/venus/wiki/dbus#tank-levels
tank:             
  ProductId:
    default: 41313 # Generic Tank Input
  CustomName:
    default: "My Tank Sensor"
    persist: true
  Status:
    description: "0=Ok; 1=Disconnected; 2=Short circuited; 3=Unknown"
    default: 0
    min: 0
    max: 3
  FluidType:
    description: |
      0=Fuel; 1=Fresh water; 2=Waste water; 3=Live well; 4=Oil; 5=Black water (sewage)
      6=Gasoline; 7=Diesel; 8=Liquid  Petroleum Gas (LPG); 9=Liquid Natural Gas (LNG)
      10=Hydraulic oil; 11=Raw water
    persist: true
    default: 1
    min: 0
    max: 11        
  Capacity:
    description: "m3"
    persist: true
    default: 0.1
    #min: 0
    #max: 9999         
  Level:            
    description: "0 to 100%" 
  Remaining:
    description: "m3"


# https://github.com/victronenergy/venus/wiki/dbus#pv-inverters
pvinverter:
  ProductId:
    default: 45069 # 0xB00D, 0xB00D, 45069 = ET340, 45068 = ET112, ESS Demo mode uses 45058
  CustomName:
    default: "My PV Inverter"
    persist: true
  ErrorCode: # https://www.victronenergy.com/live/mppt-error-codes
    description: "0=No Error"
    default: 0 # not showing in in console???
  Position:
    description: "0=AC input 1; 1=AC output; 2=AC input 2"
    persist: true
    default: 0
    min: 0
    max: 2
  StatusCode: # not used by ESS demo mode pvinverter
    description: "0=Startup 0; 1=Startup 1; 2=Startup 2; 3=Startup 3; 4=Startup 4; 5=Startup 5; 6=Startup 6; 7=Running; 8=Standby; 9=Boot loading; 10=Error"
    default: 7
    min: 0
    max: 10
  AllowedRoles:
    default: ["grid", "pvinverter", "genset", "acload"]
  Role:
    description: "grid, pvinverter, genset, acload"    
    persist: true
    default: "pvinverter"
    #  PhaseConfig:
    #    description: "0=3P.n; 1=3P.l; 2=2P; 3=1P; 4=3P"
    #    persist: true
    #    default: 0
    #    min: 0
    #    max: 4
    #  DeviceType: 
    #    description: "???"
    #    persist: true
    #    default: 71 # valued used by pvinverter in ESS demo mode
    #  Serial:
    #    description: "device serial number"
    #    persist: true
    #    default: ""
  Ac/MaxPower: # Max rated power (in Watts) of the inverter
    description: "W"
    persist: true
    default: 0
    format: "{} W"
  Ac/Energy/Forward: # Total produced energy over all phases
    description: "kWh"
    format: "{} kWh"
  Ac/Current: 
    format: "{} A"
    description: "A"
  Ac/Power: # Total power of all phases, preferably real power
    format: "{} W"
    description: "W"
  Ac/L1/Voltage:
    description: "V AC"
    format: "{} V"
  Ac/L1/Current:
    description: "A AC"
    format: "{} A"
  Ac/L1/Power:
    description: "W"
    format: "{} W"
  Ac/L1/Energy/Forward:
    description: "kWh"
    format: "{} kWh"
  Ac/L2/Voltage:
    format: "{} V"
    description: "V AC"
  Ac/L2/Current:
    format: "{} A"
    description: "A"
  Ac/L2/Power:
    description: "W"
    format: "{} W"
  Ac/L2/Energy/Forward:
    description: "kWh"
    format: "{} kWh"
  Ac/L3/Voltage:
    format: "{} V"
    description: "V AC"
  Ac/L3/Current:
    format: "{} A"
    description: "A AC"
  Ac/L3/Power:
    format: "{} W"
    description: "W"
  Ac/L3/Energy/Forward:
    format: "{} kWh"
    description: "kWh"


# https://github.com/victronenergy/venus/wiki/dbus#grid-and-genset-meter
grid:
  ProductId:
    default: 65535 # 0xFFFF
  CustomName:
    default: "My Grid Meter"
    persist: true
  ErrorCode: # https://www.victronenergy.com/live/mppt-error-codes
    description: "0=No Error"
    default: 0
  DeviceType: # ?
    description: ""
    persist: true
    default: 0
    min: 0
    max: 2
    #  AllowedRoles:
    #    default: '["grid", "pvinverter", "genset", "acload"]'
    #  Role:
    #    description: "grid, pvinverter, genset, acload"    
    #    persist: true
    #    default: "grid"
    #  PhaseConfig:
    #    description: "0=3P.n; 1=3P.l; 2=2P; 3=1P; 4=3P"
    #    persist: true
    #    default: 0
    #    min: 0
    #    max: 4
  Ac/Energy/Forward: # Total bought energy over all phases
    description: "kWh"
    format: "{} kWh"
  Ac/Energy/Reverse: # Total sold energy over all phases
    description: "kWh"
    format: "{} kWh"
  Ac/Power: # Total power of all phases, preferably real power
    description: "W"
    format: "{} W"
  Ac/Current:
    description: "A AC"
    format: "{} A"
  Ac/L1/Current:
    description: "A AC"
    format: "{} A"
  Ac/L1/Energy/Forward:
    description: "kWh"
    format: "{} kWh"
  Ac/L1/Energy/Reverse:
    description: "kWh"
    format: "{} kWh"
  Ac/L1/Power:
    description: "W"
    format: "{} W"
  Ac/L1/Voltage:
    description: "V AC"
    format: "{} V"
  Ac/L2/Current:
    description: "A AC"
    format: "{} A"
  Ac/L2/Energy/Forward:
    description: "kWh"
    format: "{} kWh"
  Ac/L2/Energy/Reverse:
    description: "kWh"
    format: "{} kWh"
  Ac/L2/Power:
    description: "W"
    format: "{} W"
  Ac/L2/Voltage:
    description: "V AC"
    format: "{} V"
  Ac/L3/Current:
    description: "A AC"
    format: "{} A"
  Ac/L3/Energy/Forward:
    description: "kWh"
    format: "{} kWh"
  Ac/L3/Energy/Reverse:
    description: "kWh"
    format: "{} kWh"
  Ac/L3/Power:
    description: "W"
    format: "{} W"
  Ac/L3/Voltage:
    description: "V AC"
    format: "{} V"

# https://github.com/victronenergy/venus/wiki/dbus#gps
gps:
  ProductId:
    default: 65535 # 0xFFFF
  CustomName:
    default: "My GPS Sensor"
    persist: true
  Position/Longitude:
    description: "Decimal degrees"
  Position/Latitude:
    description: "Decimal degrees"
  Course:
    description: "Degrees"
  Speed:
    description: "m/s"
  Fix:
    description: "0 = no fix, 1 = GPS Fix"
  Altitude:
    description: "m"
  NrOfSatellites:
    description: "Count"


# https://github.com/victronenergy/venus/wiki/dbus#evcharger
evcharger:
  ProductId:
    default: 65535 # 0xFFFF
  CustomName:
    default: "My EV Charger"
    persist: true
  Ac/Energy/Forward:
    description: "Ac Engergy Forward wh"
    format: "{:.2f}W"
  Ac/L1/Power:
    description: "L1 Power used (W)"
    format: "{} W"
  Ac/L2/Power:
    description: "L3 Power used (W)"
    format: "{} W"
  Ac/L3/Power:
    description: "L3 Power used (W)"
    format: "{} W"
  Ac/Power:
    description: "AC Power (W)"
    format: "{} W"
  AutoStart:
    description: "0=Charger autostart disabled,  1=Charger autostart enabled"
    default: 0
    persist: true
  ChargingTime:
    description: "Total charging time (seconds)"
    default: 0
    format: "{} s"
  Current:
    description: "Charging current actual (A)"
    default: 0
  EnableDisplay:
    description: "Control via display; 0=control disabled, 1=control enabled"
    default: 1
    persist: true
  MaxCurrent:
    description: "Max current (A)"
    default: 0
    persist: true 
  Mode:
    description: "0=Manual, 1=Auto"
    default: 0
    min: 0
    max: 2
    persist: true
  Model:
    description: "Model, e.g. AC22E or AC22NS (for No Screen)"
    default: "AC22NS"
  Position: # 0=AC input 1;1=AC output;2=AC input 2
    persist: true
    default: 0
    min: 0
    max: 2
  Role:
    description: "Role"
  SetCurrent: # Set charge current (manual mode)
    description: "Charging current (A)"
    persist: true
    default: 0
  StartStop: # Start/stop charging (manual mode)
    description: "Start Stop"
    default: 0
    persist: true
  Status:
    description: "0=disconnected, 1=connected, 2=charging, 3=charged,4=waiting for sun, 5=waiting for RFID, 6=waiting for start, 7=low SOC, 8=ground test error, 9=welded contacts error, 10=CP input test error (shorted), 11=residual current detected, 12=undervoltage detected, 13=overvoltage detected, 14=overheating detected, 15-19=reserved, 20=charging limit"
    default: 1
    min: 0
    max: 20

# https://github.com/victronenergy/venus/wiki/dbus#digitalinput    
digitalinput:
  ProductId:
    default: "Custom" # Generic Temperature Input
  CustomName:
    default: "My Digital Input Sensor"
    persist: true
  Status:
    default: "Off"

# https://github.com/victronenergy/venus/wiki/dbus#battery
battery:
  ProductId:
    default: 41904 # Generic Temperature Input
  CustomName:
    default: "My Smart Battery Sense"
    persist: true
  Dc/0/Voltage:
    description: "V"
    format: "{} V"
  Dc/0/Power:
    description: "W"
    format: "{} W"
  Dc/0/Current: 
    description: "A"
    format: "{} A"
  Dc/0/Temperature: 
    description: "°C"
    format: "{} °C"
  Soc: 
    description: "%"
    format: "{} %"
  Dc/1/Voltage:
    description: "V"
    format: "{} V"
  Settings/HasStarterVoltage:
    default: 1
    persist: true
  